import type { StaticImageData } from "next/image";

/** SWAP: swap category strings to match your site taxonomy. */
export type ProjectCategory =
  | "Music Videos"
  | "Commercials"
  | "Narrative"
  | "Live / Rollouts"
  | "Development";

export type ProjectPriority = "hero" | "large" | "standard" | "small";

export type ProjectSize = "xl" | "lg" | "md" | "sm";

/** Neutral placeholder for résumé entries awaiting a verified public video URL. */
const NEEDS_VIDEO_THUMB =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='480' height='360'%3E%3Crect fill='%23c5c8c2' width='480' height='360'/%3E%3C/svg%3E";

export type Project = {
  slug: string;
  tapeCode: string;
  archivalStamp?: string;
  title: string; 
  category: ProjectCategory;
  year: string;
  role: string;
  client: string;
  /** Director credit — shown in the index rail and under the open player title. */
  director: string;
  videoUrl: string;
  /** Present for YouTube sources (matches ID in videoUrl). */
  youtubeId?: string;
  vimeoId?: string;
  thumbnail: string | StaticImageData;
  thumbnailAlt: string;
  description: string;
  featured: boolean;
  priority: ProjectPriority;
  size: ProjectSize;
};

/**
 * Curated wall + archive from collindruz.com and additional reels (Apr 2026).
 * Literal array order is stable; `lib/bedroomWallLayout` assigns the wall via a manual slot map + priority score.
 */
export const projects: Project[] = [
  {
    slug: "doja-cat-gorgeous",
    tapeCode: "CDR-2503",
    archivalStamp: "MASTER",
    title: "Doja Cat — Gorgeous",
    category: "Music Videos",
    year: "2025",
    role: "Executive Producer",
    client: "Doja Cat",
    director: "Bardia Zeinali",
    videoUrl: "https://www.youtube.com/watch?v=nBJRaflBDBg",
    youtubeId: "nBJRaflBDBg",
    thumbnail: "https://img.youtube.com/vi/nBJRaflBDBg/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Gorgeous video still",
    description: "Vie — high gloss, long shadows.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "charlie-puth-thats-not-how-this-works",
    tapeCode: "CDR-2302",
    archivalStamp: "HOLD",
    title: "Charlie Puth — That's Not How This Works (short film)",
    category: "Narrative",
    year: "2023",
    role: "Producer",
    client: "Charlie Puth",
    director: "Matthew Daniel Siskin & Phillip R. Lopez",
    videoUrl: "https://www.youtube.com/watch?v=Iwbo_nzCMY8",
    youtubeId: "Iwbo_nzCMY8",
    thumbnail: "https://img.youtube.com/vi/Iwbo_nzCMY8/hqdefault.jpg",
    thumbnailAlt: "Charlie Puth short film still",
    description: "Short film for the single — wrong timing, long exhale.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "sabrina-carpenter-taste",
    tapeCode: "CDR-2401",
    archivalStamp: "LP",
    title: "Sabrina Carpenter — Taste",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "Sabrina Carpenter",
    director: "Dave Meyers",
    videoUrl: "https://www.youtube.com/watch?v=KEG7b851Ric",
    youtubeId: "KEG7b851Ric",
    thumbnail: "https://img.youtube.com/vi/KEG7b851Ric/hqdefault.jpg",
    thumbnailAlt: "Sabrina Carpenter Taste still",
    description: "Short n’ Sweet cycle — sharp edit, dry humor.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "lil-dicky-hahaha-i-love-myself",
    tapeCode: "CDR-2501",
    archivalStamp: "TC",
    title: "Lil Dicky — HAHAHA / I Love Myself (music short film)",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Lil Dicky",
    director: "Phillip R. Lopez",
    videoUrl: "https://www.youtube.com/watch?v=MFvJyhv4QUE",
    youtubeId: "MFvJyhv4QUE",
    thumbnail: "https://img.youtube.com/vi/MFvJyhv4QUE/hqdefault.jpg",
    thumbnailAlt: "Lil Dicky music short film still",
    description: "Director’s cut — PENITH world, two-track knot.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "mercedes-benz-jon-rahm-burmester",
    tapeCode: "CDR-2301",
    archivalStamp: "MASTER",
    title: "Mercedes-Benz x Jon Rahm — Energizing Comfort / Burmester",
    category: "Commercials",
    year: "2023",
    role: "Producer",
    client: "Mercedes-Benz",
    director: "Calvin Pausania",
    videoUrl: "https://www.youtube.com/watch?v=6U8bgLcBmok",
    youtubeId: "6U8bgLcBmok",
    thumbnail: "https://img.youtube.com/vi/6U8bgLcBmok/hqdefault.jpg",
    thumbnailAlt: "Mercedes-Benz Burmester with Jon Rahm still",
    description: "Pre-swing hush — cabin, Burmester, distractions dialed down.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "burger-king-whopper-by-you",
    tapeCode: "CDR-2506",
    title: "Burger King — Whopper By You",
    category: "Commercials",
    year: "2025",
    role: "Producer",
    client: "Burger King",
    director: "Justin Abernethy",
    videoUrl: "https://www.youtube.com/watch?v=4_xj1oCWn_8",
    youtubeId: "4_xj1oCWn_8",
    thumbnail: "https://img.youtube.com/vi/4_xj1oCWn_8/hqdefault.jpg",
    thumbnailAlt: "Burger King Whopper By You still",
    description: "Whopper By You — built-for-you read, fast table.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "rem-beauty-chapter-1-ultraviolet",
    tapeCode: "CDR-2101",
    archivalStamp: "SP",
    title: "r.e.m. beauty — chapter 1: ultraviolet",
    category: "Commercials",
    year: "2021",
    role: "Producer",
    client: "r.e.m. beauty",
    director: "Ruth Hogben",
    videoUrl: "https://www.youtube.com/watch?v=gvjsx8PZVkI",
    youtubeId: "gvjsx8PZVkI",
    thumbnail: "https://img.youtube.com/vi/gvjsx8PZVkI/hqdefault.jpg",
    thumbnailAlt: "r.e.m. beauty chapter one launch still",
    description: "Chapter one launch — product, violet light, quiet sell.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "sabrina-carpenter-tears",
    tapeCode: "CDR-2507",
    archivalStamp: "SP",
    title: "Sabrina Carpenter — Tears",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Sabrina Carpenter",
    director: "Bardia Zeinali",
    videoUrl: "https://www.youtube.com/watch?v=V9vuCByb6js",
    youtubeId: "V9vuCByb6js",
    thumbnail: "https://img.youtube.com/vi/V9vuCByb6js/hqdefault.jpg",
    thumbnailAlt: "Sabrina Carpenter Tears still",
    description: "Man’s Best Friend era — dry-eyed hook.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "doja-cat-stranger",
    tapeCode: "CDR-2504",
    title: "Doja Cat — Stranger",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Doja Cat",
    director: "Dave Meyers",
    videoUrl: "https://www.youtube.com/watch?v=U-124RmcV7I",
    youtubeId: "U-124RmcV7I",
    thumbnail: "https://img.youtube.com/vi/U-124RmcV7I/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Stranger still",
    description: "Vie — stranger-in-the-house tableaux, slow voltage.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "doja-cat-jealous-type",
    tapeCode: "CDR-2505",
    archivalStamp: "DUB",
    title: "Doja Cat — Jealous Type",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Doja Cat",
    director: "Boni Mata",
    videoUrl: "https://www.youtube.com/watch?v=lv1MwS56aCo",
    youtubeId: "lv1MwS56aCo",
    thumbnail: "https://img.youtube.com/vi/lv1MwS56aCo/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Jealous Type still",
    description: "Vie — tight lens, controlled heat.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "smirnoff-live-louder-karol-g",
    tapeCode: "CDR-2602",
    title: "Smirnoff — Live Louder (Karol G)",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Smirnoff",
    director: "Jessy Terrero",
    videoUrl: "https://www.youtube.com/watch?v=b7yEC_186ZM",
    youtubeId: "b7yEC_186ZM",
    thumbnail: "https://img.youtube.com/vi/b7yEC_186ZM/hqdefault.jpg",
    thumbnailAlt: "Smirnoff Karol G spot still",
    description: "Live louder — Karol G, night pulse.",
    featured: true,
    priority: "hero",
    size: "sm",
  },
  {
    slug: "mgk-trippie-redd-beauty",
    tapeCode: "CDR-2603",
    title: "mgk & Trippie Redd — beauty",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "mgk / Trippie Redd",
    director: "Philip R. Lopez",
    videoUrl: "https://www.youtube.com/watch?v=Y5a59wE3JYU",
    youtubeId: "Y5a59wE3JYU",
    thumbnail: "https://img.youtube.com/vi/Y5a59wE3JYU/hqdefault.jpg",
    thumbnailAlt: "mgk Trippie Redd beauty still",
    description: "Official video — beauty.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "halsey-so-good",
    tapeCode: "CDR-2604",
    title: "Halsey — So Good",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Halsey",
    director: "Alev Aydin",
    videoUrl: "https://www.youtube.com/watch?v=N6tv11_KMiM",
    youtubeId: "N6tv11_KMiM",
    thumbnail: "https://img.youtube.com/vi/N6tv11_KMiM/hqdefault.jpg",
    thumbnailAlt: "Halsey So Good still",
    description: "Official video — So Good.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "le-sserafim-easy",
    tapeCode: "CDR-2605",
    title: "LE SSERAFIM — EASY",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "LE SSERAFIM",
    director: "Nina McNeely",
    videoUrl: "https://www.youtube.com/watch?v=bNKXxwOQYB8",
    youtubeId: "bNKXxwOQYB8",
    thumbnail: "https://img.youtube.com/vi/bNKXxwOQYB8/hqdefault.jpg",
    thumbnailAlt: "LE SSERAFIM EASY still",
    description: "Official MV — EASY.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "doja-cat-agora-hills",
    tapeCode: "CDR-2606",
    title: "Doja Cat — Agora Hills",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Doja Cat",
    director: "Hannah Lux Davis & Doja Cat",
    videoUrl: "https://www.youtube.com/watch?v=0c66ksfigtU",
    youtubeId: "0c66ksfigtU",
    thumbnail: "https://img.youtube.com/vi/0c66ksfigtU/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Agora Hills still",
    description: "Official video — Agora Hills.",
    featured: true,
    priority: "hero",
    size: "lg",
  },
  {
    slug: "sza-nobody-gets-me",
    tapeCode: "CDR-2607",
    title: "SZA — Nobody Gets Me",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "SZA",
    director: "Bradley J. Calder",
    videoUrl: "https://www.youtube.com/watch?v=NNd_ufPG3x4",
    youtubeId: "NNd_ufPG3x4",
    thumbnail: "https://img.youtube.com/vi/NNd_ufPG3x4/hqdefault.jpg",
    thumbnailAlt: "SZA Nobody Gets Me still",
    description: "Official video — Nobody Gets Me.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "kenzie-100-degrees",
    tapeCode: "CDR-2608",
    title: "kenzie — 100 degrees",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "kenzie",
    director: "Boni Mata",
    videoUrl: "https://www.youtube.com/watch?v=VP8_YT4FKkQ",
    youtubeId: "VP8_YT4FKkQ",
    thumbnail: "https://img.youtube.com/vi/VP8_YT4FKkQ/hqdefault.jpg",
    thumbnailAlt: "kenzie 100 degrees still",
    description: "Official music video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "sza-psa-teaser",
    tapeCode: "CDR-2609",
    title: "SZA — PSA (teaser)",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "SZA",
    director: "Bradley J. Calder",
    videoUrl: "https://www.youtube.com/watch?v=fC06V0ZLGwg",
    youtubeId: "fC06V0ZLGwg",
    thumbnail: "https://img.youtube.com/vi/fC06V0ZLGwg/hqdefault.jpg",
    thumbnailAlt: "SZA PSA teaser still",
    description: "Official teaser.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "charlie-puth-thats-not-how-this-works-dan-shay",
    tapeCode: "CDR-2610",
    title: "Charlie Puth — That's Not How This Works (feat. Dan + Shay)",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Charlie Puth",
    director: "Phillip R. Lopez",
    videoUrl: "https://www.youtube.com/watch?v=PAKFzFqJa58",
    youtubeId: "PAKFzFqJa58",
    thumbnail: "https://img.youtube.com/vi/PAKFzFqJa58/hqdefault.jpg",
    thumbnailAlt: "Charlie Puth Dan + Shay video still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "renee-rapp-snow-angel",
    tapeCode: "CDR-2611",
    title: "Reneé Rapp — Snow Angel",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Reneé Rapp",
    director: "Alyah Chanelle Scott",
    videoUrl: "https://www.youtube.com/watch?v=WZEHXFIa7Bk",
    youtubeId: "WZEHXFIa7Bk",
    thumbnail: "https://img.youtube.com/vi/WZEHXFIa7Bk/hqdefault.jpg",
    thumbnailAlt: "Reneé Rapp Snow Angel still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "honda-hr-v-twofold-mike-carson",
    tapeCode: "CDR-2613",
    title: "Honda HR-V — twofold (Mike Carson)",
    category: "Commercials",
    year: "2023",
    role: "Producer",
    client: "Honda",
    director: "Mike Carson",
    videoUrl: "https://www.youtube.com/watch?v=0xJjZSE39CU",
    youtubeId: "0xJjZSE39CU",
    thumbnail: "https://img.youtube.com/vi/0xJjZSE39CU/hqdefault.jpg",
    thumbnailAlt: "Honda HR-V spot still",
    description: "HR-V — twofold with Mike Carson.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "asap-rocky-pacsun",
    tapeCode: "CDR-2615",
    title: "A$AP Rocky — PacSun",
    category: "Commercials",
    year: "2022",
    role: "Producer",
    client: "PacSun",
    director: "A$AP Rocky & Aisultan Seitov",
    videoUrl: "https://www.youtube.com/watch?v=LVZagKk2mvI",
    youtubeId: "LVZagKk2mvI",
    thumbnail: "https://img.youtube.com/vi/LVZagKk2mvI/hqdefault.jpg",
    thumbnailAlt: "A$AP Rocky PacSun still",
    description: "Brand film — Rocky, PacSun.",
    featured: true,
    priority: "large",
    size: "lg",
  },
  {
    slug: "cadillac-lyriq-womens-history-month-goyo",
    tapeCode: "CDR-2616",
    title: "Cadillac LYRIQ — Women's History Month (Goyo)",
    category: "Commercials",
    year: "2023",
    role: "Producer",
    client: "Cadillac",
    director: "Jessy Terrero",
    videoUrl: "https://www.youtube.com/watch?v=Z1PluYiQHDM",
    youtubeId: "Z1PluYiQHDM",
    thumbnail: "https://img.youtube.com/vi/Z1PluYiQHDM/hqdefault.jpg",
    thumbnailAlt: "Cadillac LYRIQ film still",
    description: "LYRIQ x Goyo — Women's History Month.",
    featured: true,
    priority: "large",
    size: "lg",
  },
  {
    slug: "jack-harlow-nail-tech",
    tapeCode: "CDR-2617",
    title: "Jack Harlow — Nail Tech",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Jack Harlow",
    director: "Frank Borin & Jack Harlow",
    videoUrl: "https://www.youtube.com/watch?v=e2AeKIzfQus",
    youtubeId: "e2AeKIzfQus",
    thumbnail: "https://img.youtube.com/vi/e2AeKIzfQus/hqdefault.jpg",
    thumbnailAlt: "Jack Harlow Nail Tech still",
    description: "Official video.",
    featured: true,
    priority: "hero",
    size: "lg",
  },
  {
    slug: "saweetie-closer-feat-her",
    tapeCode: "CDR-2618",
    title: "Saweetie — Closer (feat. H.E.R.)",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Saweetie",
    director: "Hannah Lux Davis",
    videoUrl: "https://www.youtube.com/watch?v=ALO5efsHHQA",
    youtubeId: "ALO5efsHHQA",
    thumbnail: "https://img.youtube.com/vi/ALO5efsHHQA/hqdefault.jpg",
    thumbnailAlt: "Saweetie Closer still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "netflix-slate-true-crime",
    tapeCode: "CDR-2620",
    title: "Netflix — Home of True Crime (Slate)",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Netflix",
    director: "Tanu Muino",
    videoUrl: "https://www.youtube.com/watch?v=Yo3WUYBcNJI",
    youtubeId: "Yo3WUYBcNJI",
    thumbnail: "https://img.youtube.com/vi/Yo3WUYBcNJI/hqdefault.jpg",
    thumbnailAlt: "Netflix true crime slate still",
    description: "Slate announcement — true crime positioning.",
    featured: true,
    priority: "large",
    size: "lg",
  },
  {
    slug: "avril-lavigne-bite-me",
    tapeCode: "CDR-2621",
    title: "Avril Lavigne — Bite Me",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Avril Lavigne",
    director: "Hannah Lux Davis",
    videoUrl: "https://www.youtube.com/watch?v=ciqUEV9F0OY",
    youtubeId: "ciqUEV9F0OY",
    thumbnail: "https://img.youtube.com/vi/ciqUEV9F0OY/hqdefault.jpg",
    thumbnailAlt: "Avril Bite Me still",
    description: "Official video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "addison-rae-obsessed",
    tapeCode: "CDR-2622",
    title: "Addison Rae — Obsessed",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Addison Rae",
    director: "Diane Martel",
    videoUrl: "https://www.youtube.com/watch?v=PHr72DM762k",
    youtubeId: "PHr72DM762k",
    thumbnail: "https://img.youtube.com/vi/PHr72DM762k/hqdefault.jpg",
    thumbnailAlt: "Addison Rae Obsessed still",
    description: "Official music video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "travis-scott-ps5-unboxing-reimagined",
    tapeCode: "CDR-2623",
    title: "Travis Scott + Cactus Jack — PS5: Unboxing Reimagined",
    category: "Commercials",
    year: "2020",
    role: "Producer",
    client: "PlayStation / Travis Scott",
    director: "Warren Fu",
    videoUrl: "https://www.youtube.com/watch?v=dIaDGfE0G2A",
    youtubeId: "dIaDGfE0G2A",
    thumbnail: "https://img.youtube.com/vi/dIaDGfE0G2A/hqdefault.jpg",
    thumbnailAlt: "PS5 Travis Scott unboxing still",
    description: "Unboxing reimagined — Cactus Jack x PS5.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "travis-barker-gimme-brain",
    tapeCode: "CDR-2625",
    title: "Travis Barker — Gimme Brain (feat. Lil Wayne & Rick Ross)",
    category: "Music Videos",
    year: "2019",
    role: "Producer",
    client: "Travis Barker",
    director: "Andrew Sandler",
    videoUrl: "https://www.youtube.com/watch?v=EXj_23pCUmE",
    youtubeId: "EXj_23pCUmE",
    thumbnail: "https://img.youtube.com/vi/EXj_23pCUmE/hqdefault.jpg",
    thumbnailAlt: "Travis Barker Gimme Brain still",
    description: "WSHH exclusive official video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "brandy-starting-now",
    tapeCode: "CDR-2626",
    title: "Brandy — Starting Now",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Brandy",
    director: "Tusk",
    videoUrl: "https://www.youtube.com/watch?v=7Ms-Y99bAi0",
    youtubeId: "7Ms-Y99bAi0",
    thumbnail: "https://img.youtube.com/vi/7Ms-Y99bAi0/hqdefault.jpg",
    thumbnailAlt: "Brandy Starting Now still",
    description: "Official video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "rich-brian-love-in-my-pocket",
    tapeCode: "CDR-2627",
    title: "Rich Brian — Love In My Pocket",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Rich Brian",
    director: "Daniel \"Cloud\" Campos",
    videoUrl: "https://www.youtube.com/watch?v=oFHONLjD4MM",
    youtubeId: "oFHONLjD4MM",
    thumbnail: "https://img.youtube.com/vi/oFHONLjD4MM/hqdefault.jpg",
    thumbnailAlt: "Rich Brian Love In My Pocket still",
    description: "Official music video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "higher-learning-podcast-frequency",
    tapeCode: "CDR-2629",
    title: "Spotify — This Is Our Frequency: Higher Learning",
    category: "Commercials",
    year: "2021",
    role: "Producer",
    client: "Spotify",
    director: "Mike Carson",
    videoUrl: "https://www.youtube.com/watch?v=7ldm7FfUMM0",
    youtubeId: "7ldm7FfUMM0",
    thumbnail: "https://img.youtube.com/vi/7ldm7FfUMM0/hqdefault.jpg",
    thumbnailAlt: "Spotify Frequency Higher Learning still",
    description: "Frequency launch spot — HPLA.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "joji-diplo-daylight",
    tapeCode: "CDR-2630",
    title: "Joji & Diplo — Daylight",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Joji / Diplo",
    director: "Munachi Osegbu",
    videoUrl: "https://www.youtube.com/watch?v=v97FPN2US2o",
    youtubeId: "v97FPN2US2o",
    thumbnail: "https://img.youtube.com/vi/v97FPN2US2o/hqdefault.jpg",
    thumbnailAlt: "Joji Diplo Daylight still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "vince-staples-law-of-averages",
    tapeCode: "CDR-2631",
    title: "Vince Staples — LAW OF AVERAGES",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Vince Staples",
    director: "Glenn Michael & Christo Anesti",
    videoUrl: "https://www.youtube.com/watch?v=oTri3zbX-R8",
    youtubeId: "oTri3zbX-R8",
    thumbnail: "https://img.youtube.com/vi/oTri3zbX-R8/hqdefault.jpg",
    thumbnailAlt: "Vince Staples Law of Averages still",
    description: "Official video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "charlie-puth-free-one-and-only-ivan",
    tapeCode: "CDR-2635",
    title: "Charlie Puth — Free (The One and Only Ivan)",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Charlie Puth",
    director: "Disney Music (promo)",
    videoUrl: "https://www.youtube.com/watch?v=QoohbHFIS38",
    youtubeId: "QoohbHFIS38",
    thumbnail: "https://img.youtube.com/vi/QoohbHFIS38/hqdefault.jpg",
    thumbnailAlt: "Charlie Puth Free still",
    description: "From The One and Only Ivan.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "madeintyo-bet-uncut",
    tapeCode: "CDR-2641",
    title: "MadeinTYO — BET Uncut (feat. Chance the Rapper & Smino)",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "MadeinTYO",
    director: "FilthyMcDave",
    videoUrl: "https://www.youtube.com/watch?v=WxsWU2_btic",
    youtubeId: "WxsWU2_btic",
    thumbnail: "https://img.youtube.com/vi/WxsWU2_btic/hqdefault.jpg",
    thumbnailAlt: "MadeinTYO BET Uncut still",
    description: "Official video.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "why-dont-we-slow-down",
    tapeCode: "CDR-2642",
    title: "Why Don't We — Slow Down",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Why Don't We",
    director: "Isaac Rentz",
    videoUrl: "https://www.youtube.com/watch?v=46ISK1g54Fc",
    youtubeId: "46ISK1g54Fc",
    thumbnail: "https://img.youtube.com/vi/46ISK1g54Fc/hqdefault.jpg",
    thumbnailAlt: "Why Don't We Slow Down still",
    description: "Official music video.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "jean-dawson-sick-of-it",
    tapeCode: "CDR-2643",
    title: "Jean Dawson — SICK OF IT*",
    category: "Music Videos",
    year: "2022",
    role: "Executive Producer",
    client: "Jean Dawson",
    director: "Bradley J. Calder",
    videoUrl: "https://www.youtube.com/watch?v=e8cOvgIpcHw",
    youtubeId: "e8cOvgIpcHw",
    thumbnail: "https://img.youtube.com/vi/e8cOvgIpcHw/hqdefault.jpg",
    thumbnailAlt: "Jean Dawson SICK OF IT still",
    description: "Official video — CHAOS NOW*.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "jean-dawson-pirate-radio",
    tapeCode: "CDR-2644",
    title: "Jean Dawson — PIRATE RADIO*",
    category: "Music Videos",
    year: "2022",
    role: "Executive Producer",
    client: "Jean Dawson",
    director: "Bradley J. Calder",
    videoUrl: "https://www.youtube.com/watch?v=_dYC6QndB2o",
    youtubeId: "_dYC6QndB2o",
    thumbnail: "https://img.youtube.com/vi/_dYC6QndB2o/hqdefault.jpg",
    thumbnailAlt: "Jean Dawson PIRATE RADIO still",
    description: "Official video — CHAOS NOW*.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "jean-dawson-three-heads",
    tapeCode: "CDR-2645",
    title: "Jean Dawson — THREE HEADS*",
    category: "Music Videos",
    year: "2022",
    role: "Executive Producer",
    client: "Jean Dawson",
    director: "Bradley J. Calder",
    videoUrl: "https://www.youtube.com/watch?v=lcXt5tU_QM8",
    youtubeId: "lcXt5tU_QM8",
    thumbnail: "https://img.youtube.com/vi/lcXt5tU_QM8/hqdefault.jpg",
    thumbnailAlt: "Jean Dawson THREE HEADS still",
    description: "Official video — CHAOS NOW*.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "spotify-live-room-series-2026",
    tapeCode: "CDR-2646",
    archivalStamp: "NEEDS_VIDEO",
    title: "Spotify — Live Room Series",
    category: "Commercials",
    year: "2026",
    role: "Producer",
    client: "Spotify",
    director: "Various Directors",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Spotify Live Room Series — video pending",
    description: "Freenjoy.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "nike-hoops-hotline-la",
    tapeCode: "CDR-2647",
    archivalStamp: "NEEDS_VIDEO",
    title: "Nike — Hoops Hotline LA",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Nike",
    director: "Mike Carson",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Nike Hoops Hotline LA — video pending",
    description: "HPLA.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "urban-decay-campaign-1",
    tapeCode: "CDR-2648",
    archivalStamp: "NEEDS_VIDEO",
    title: "Urban Decay — Campaign 1",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Urban Decay",
    director: "Hannah Lux Davis",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Urban Decay Campaign 1 — video pending",
    description: "London Alley.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "urban-decay-campaign-2",
    tapeCode: "CDR-2649",
    archivalStamp: "NEEDS_VIDEO",
    title: "Urban Decay — Campaign 2",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Urban Decay",
    director: "Hannah Lux Davis",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Urban Decay Campaign 2 — video pending",
    description: "London Alley.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "martin-reunion-promo",
    tapeCode: "CDR-2650",
    archivalStamp: "NEEDS_VIDEO",
    title: "Martin — Reunion Promo",
    category: "Commercials",
    year: "2022",
    role: "Producer",
    client: "Martin",
    director: "Chris Robinson",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Martin Reunion Promo — video pending",
    description: "Robot Films.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "spotify-frequency-amorphous",
    tapeCode: "CDR-2651",
    archivalStamp: "NEEDS_VIDEO",
    title: "Spotify — This Is Our Frequency: Amorphous",
    category: "Commercials",
    year: "2021",
    role: "Producer",
    client: "Spotify",
    director: "Mike Carson",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Spotify Frequency Amorphous — video pending",
    description: "HPLA.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "spotify-frequency-yung-baby-tate",
    tapeCode: "CDR-2652",
    archivalStamp: "NEEDS_VIDEO",
    title: "Spotify — This Is Our Frequency: Yung Baby Tate",
    category: "Commercials",
    year: "2021",
    role: "Producer",
    client: "Spotify",
    director: "Mike Carson",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Spotify Frequency Yung Baby Tate — video pending",
    description: "HPLA.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "google-samsung-galaxy-z-fold3-flip3",
    tapeCode: "CDR-2653",
    archivalStamp: "NEEDS_VIDEO",
    title: "Google × Samsung — Galaxy Z Fold3 / Flip3",
    category: "Commercials",
    year: "2021",
    role: "Production Manager",
    client: "Google × Samsung",
    director: "Walt Becker",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Google Samsung Galaxy Z Fold3 Flip3 — video pending",
    description: "Panay Films.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "tmobile-team-anthony-anderson-vs-team-mama",
    tapeCode: "CDR-2654",
    archivalStamp: "NEEDS_VIDEO",
    title: "T-Mobile — Team Anthony Anderson vs. Team Mama",
    category: "Commercials",
    year: "2021",
    role: "Production Manager",
    client: "T-Mobile",
    director: "Steve Pink",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "T-Mobile Team Anthony Anderson vs Team Mama — video pending",
    description: "Panay Films.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "tmobile-costume-party",
    tapeCode: "CDR-2655",
    archivalStamp: "NEEDS_VIDEO",
    title: "T-Mobile — Costume Party",
    category: "Commercials",
    year: "2021",
    role: "Production Manager",
    client: "T-Mobile",
    director: "Walt Becker",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "T-Mobile Costume Party — video pending",
    description: "Panay Films.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "barefoot-wine-mindy-kaling-campaign",
    tapeCode: "CDR-2656",
    archivalStamp: "NEEDS_VIDEO",
    title: "Barefoot Wine — Mindy Kaling Campaign",
    category: "Commercials",
    year: "2020",
    role: "Production Manager",
    client: "Barefoot Wine",
    director: "Michael Spiller",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Barefoot Wine Mindy Kaling Campaign — video pending",
    description: "Production Manager.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "lennon-commercial",
    tapeCode: "CDR-2657",
    archivalStamp: "NEEDS_VIDEO",
    title: "Lennon — Commercial",
    category: "Commercials",
    year: "2020",
    role: "Production Manager",
    client: "Lennon",
    director: "Tim Erem",
    videoUrl: "",
    thumbnail: NEEDS_VIDEO_THUMB,
    thumbnailAlt: "Lennon Commercial — video pending",
    description: "Dictator.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "drake-plot-twist",
    tapeCode: "CDR-2658",
    title: "Drake — Plot Twist",
    category: "Music Videos",
    year: "2026",
    role: "Producer",
    client: "Drake",
    director: "Theo Skudra",
    videoUrl: "https://www.youtube.com/watch?v=QW29Ly55Kvs",
    youtubeId: "QW29Ly55Kvs",
    thumbnail: "https://img.youtube.com/vi/QW29Ly55Kvs/hqdefault.jpg",
    thumbnailAlt: "Drake Plot Twist still",
    description: "Denim × Freenjoy.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "offset-jid-bodies",
    tapeCode: "CDR-2659",
    title: "Offset ft. JID — Bodies",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Offset",
    director: "Onda",
    videoUrl: "https://www.youtube.com/watch?v=_hkoMopfRJU",
    youtubeId: "_hkoMopfRJU",
    thumbnail: "https://img.youtube.com/vi/_hkoMopfRJU/hqdefault.jpg",
    thumbnailAlt: "Offset ft JID Bodies still",
    description: "ProdCo × Freenjoy.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "jesse-jo-stark-who-knew",
    tapeCode: "CDR-2660",
    title: "Jesse Jo Stark ft. Lil Yachty — Who Knew",
    category: "Music Videos",
    year: "2025",
    role: "EP / Producer",
    client: "Jesse Jo Stark",
    director: "Jesse Jo Stark",
    videoUrl: "https://www.youtube.com/watch?v=Xqa30OaBIKk",
    youtubeId: "Xqa30OaBIKk",
    thumbnail: "https://img.youtube.com/vi/Xqa30OaBIKk/hqdefault.jpg",
    thumbnailAlt: "Jesse Jo Stark Who Knew still",
    description: "Freenjoy.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "megan-thee-stallion-bigger-in-texas",
    tapeCode: "CDR-2661",
    title: "Megan Thee Stallion — Bigger in Texas",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "Megan Thee Stallion",
    director: "Julian Klincewicz",
    videoUrl: "https://www.youtube.com/watch?v=QxTkZTLWdo4",
    youtubeId: "QxTkZTLWdo4",
    thumbnail: "https://img.youtube.com/vi/QxTkZTLWdo4/hqdefault.jpg",
    thumbnailAlt: "Megan Thee Stallion Bigger in Texas still",
    description: "Freenjoy.",
    featured: false,
    priority: "standard",
    size: "md",
  },
];

export function getYoutubeVideoId(videoUrl: string): string | null {
  const m = videoUrl.match(
    /(?:youtube\.com\/watch\?[^#]*?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
  );
  return m ? m[1] : null;
}

export function getVimeoVideoId(videoUrl: string): string | null {
  const m = videoUrl.match(/vimeo\.com\/(?:video\/)?(\d+)/);
  return m ? m[1] : null;
}

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

/** Same order as `projects` in this file (stable list reference — do not mutate). */
export function getProjectsForArchive(): Project[] {
  return projects;
}

export type VideoEmbed =
  | { kind: "youtube"; src: string }
  | { kind: "vimeo"; src: string }
  | { kind: "file"; src: string }
  | { kind: "unknown"; src: null };

/**
 * SWAP: extend if you host elsewhere (Wistia, etc.).
 */
export function getVideoEmbed(videoUrl: string): VideoEmbed {
  const yt = videoUrl.match(
    /(?:youtube\.com\/watch\?[^#]*?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
  );
  if (yt) {
    return {
      kind: "youtube",
      src: `https://www.youtube.com/embed/${yt[1]}?rel=0&modestbranding=1`,
    };
  }
  const vm = videoUrl.match(/vimeo\.com\/(?:video\/)?(\d+)/);
  if (vm) {
    return {
      kind: "vimeo",
      src: `https://player.vimeo.com/video/${vm[1]}?badge=0`,
    };
  }
  if (/\.(mp4|webm|ogg)(\?|$)/i.test(videoUrl)) {
    return { kind: "file", src: videoUrl };
  }
  return { kind: "unknown", src: null };
}
