import type { StaticImageData } from "next/image";

/** SWAP: swap category strings to match your site taxonomy. */
export type ProjectCategory =
  | "Music Videos"
  | "Commercials"
  | "Narrative"
  | "Live / Rollouts"
  | "Development";

export type ProjectPriority = "hero" | "large" | "standard" | "small";

export type ProjectSize = "xl" | "lg" | "md" | "sm";

export type Project = {
  slug: string;
  tapeCode: string;
  archivalStamp?: string;
  title: string;
  category: ProjectCategory;
  year: string;
  role: string;
  client: string;
  videoUrl: string;
  /** Present for YouTube sources (matches ID in videoUrl). */
  youtubeId?: string;
  vimeoId?: string;
  thumbnail: string | StaticImageData;
  thumbnailAlt: string;
  description: string;
  featured: boolean;
  priority: ProjectPriority;
  size: ProjectSize;
};

/**
 * Curated wall + archive from collindruz.com and additional reels (Apr 2026).
 * Literal array order is stable; BedroomWall assigns prominent slots by priority/size.
 */
export const projects: Project[] = [
  {
    slug: "doja-cat-gorgeous",
    tapeCode: "CDR-2503",
    archivalStamp: "MASTER",
    title: "Doja Cat — Gorgeous",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Doja Cat",
    videoUrl: "https://www.youtube.com/watch?v=nBJRaflBDBg",
    youtubeId: "nBJRaflBDBg",
    thumbnail: "https://img.youtube.com/vi/nBJRaflBDBg/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Gorgeous video still",
    description: "Vie — high gloss, long shadows.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "charlie-puth-thats-not-how-this-works",
    tapeCode: "CDR-2302",
    archivalStamp: "HOLD",
    title: "Charlie Puth — That's Not How This Works (short film)",
    category: "Narrative",
    year: "2023",
    role: "Producer",
    client: "Charlie Puth",
    videoUrl: "https://www.youtube.com/watch?v=Iwbo_nzCMY8",
    youtubeId: "Iwbo_nzCMY8",
    thumbnail: "https://img.youtube.com/vi/Iwbo_nzCMY8/hqdefault.jpg",
    thumbnailAlt: "Charlie Puth short film still",
    description: "Short film for the single — wrong timing, long exhale.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "sabrina-carpenter-taste",
    tapeCode: "CDR-2401",
    archivalStamp: "LP",
    title: "Sabrina Carpenter — Taste",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "Sabrina Carpenter",
    videoUrl: "https://www.youtube.com/watch?v=KEG7b851Ric",
    youtubeId: "KEG7b851Ric",
    thumbnail: "https://img.youtube.com/vi/KEG7b851Ric/hqdefault.jpg",
    thumbnailAlt: "Sabrina Carpenter Taste still",
    description: "Short n’ Sweet cycle — sharp edit, dry humor.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "lil-dicky-hahaha-i-love-myself",
    tapeCode: "CDR-2501",
    archivalStamp: "TC",
    title: "Lil Dicky — HAHAHA / I Love Myself (music short film)",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Lil Dicky",
    videoUrl: "https://www.youtube.com/watch?v=MFvJyhv4QUE",
    youtubeId: "MFvJyhv4QUE",
    thumbnail: "https://img.youtube.com/vi/MFvJyhv4QUE/hqdefault.jpg",
    thumbnailAlt: "Lil Dicky music short film still",
    description: "Director’s cut — PENITH world, two-track knot.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "mercedes-benz-jon-rahm-burmester",
    tapeCode: "CDR-2301",
    archivalStamp: "MASTER",
    title: "Mercedes-Benz x Jon Rahm — Energizing Comfort / Burmester",
    category: "Commercials",
    year: "2023",
    role: "Producer",
    client: "Mercedes-Benz",
    videoUrl: "https://www.youtube.com/watch?v=6U8bgLcBmok",
    youtubeId: "6U8bgLcBmok",
    thumbnail: "https://img.youtube.com/vi/6U8bgLcBmok/hqdefault.jpg",
    thumbnailAlt: "Mercedes-Benz Burmester with Jon Rahm still",
    description: "Pre-swing hush — cabin, Burmester, distractions dialed down.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "burger-king-whopper-by-you",
    tapeCode: "CDR-2506",
    title: "Burger King — Whopper By You",
    category: "Commercials",
    year: "2025",
    role: "Producer",
    client: "Burger King",
    videoUrl: "https://www.youtube.com/watch?v=QVha7YSWBvc",
    youtubeId: "QVha7YSWBvc",
    thumbnail: "https://img.youtube.com/vi/QVha7YSWBvc/hqdefault.jpg",
    thumbnailAlt: "Burger King Whopper By You still",
    description: "Whopper By You — built-for-you read, fast table.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "rem-beauty-chapter-1-ultraviolet",
    tapeCode: "CDR-2101",
    archivalStamp: "SP",
    title: "r.e.m. beauty — chapter 1: ultraviolet",
    category: "Commercials",
    year: "2021",
    role: "Producer",
    client: "r.e.m. beauty",
    videoUrl: "https://www.youtube.com/watch?v=gvjsx8PZVkI",
    youtubeId: "gvjsx8PZVkI",
    thumbnail: "https://img.youtube.com/vi/gvjsx8PZVkI/hqdefault.jpg",
    thumbnailAlt: "r.e.m. beauty chapter one launch still",
    description: "Chapter one launch — product, violet light, quiet sell.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "sabrina-carpenter-tears",
    tapeCode: "CDR-2507",
    archivalStamp: "SP",
    title: "Sabrina Carpenter — Tears",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Sabrina Carpenter",
    videoUrl: "https://www.youtube.com/watch?v=V9vuCByb6js",
    youtubeId: "V9vuCByb6js",
    thumbnail: "https://img.youtube.com/vi/V9vuCByb6js/hqdefault.jpg",
    thumbnailAlt: "Sabrina Carpenter Tears still",
    description: "Man’s Best Friend era — dry-eyed hook.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "doja-cat-stranger",
    tapeCode: "CDR-2504",
    title: "Doja Cat — Stranger",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Doja Cat",
    videoUrl: "https://www.youtube.com/watch?v=U-124RmcV7I",
    youtubeId: "U-124RmcV7I",
    thumbnail: "https://img.youtube.com/vi/U-124RmcV7I/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Stranger still",
    description: "Vie — stranger-in-the-house tableaux, slow voltage.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "doja-cat-jealous-type",
    tapeCode: "CDR-2505",
    archivalStamp: "DUB",
    title: "Doja Cat — Jealous Type",
    category: "Music Videos",
    year: "2025",
    role: "Producer",
    client: "Doja Cat",
    videoUrl: "https://www.youtube.com/watch?v=lv1MwS56aCo",
    youtubeId: "lv1MwS56aCo",
    thumbnail: "https://img.youtube.com/vi/lv1MwS56aCo/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Jealous Type still",
    description: "Vie — tight lens, controlled heat.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "leboncoin-nouvelle-campagne",
    tapeCode: "CDR-2601",
    title: "le bon coin — pour tous (campaign)",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "leboncoin",
    videoUrl: "https://www.youtube.com/watch?v=nAiqPOT8ohA",
    youtubeId: "nAiqPOT8ohA",
    thumbnail: "https://img.youtube.com/vi/nAiqPOT8ohA/hqdefault.jpg",
    thumbnailAlt: "leboncoin campaign still",
    description: "Brand film — le bon _____ pour tous.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "smirnoff-live-louder-karol-g",
    tapeCode: "CDR-2602",
    title: "Smirnoff — Live Louder (Karol G)",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Smirnoff",
    videoUrl: "https://www.youtube.com/watch?v=b7yEC_186ZM",
    youtubeId: "b7yEC_186ZM",
    thumbnail: "https://img.youtube.com/vi/b7yEC_186ZM/hqdefault.jpg",
    thumbnailAlt: "Smirnoff Karol G spot still",
    description: "Live louder — Karol G, night pulse.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "mgk-trippie-redd-beauty",
    tapeCode: "CDR-2603",
    title: "mgk & Trippie Redd — beauty",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "mgk / Trippie Redd",
    videoUrl: "https://www.youtube.com/watch?v=Y5a59wE3JYU",
    youtubeId: "Y5a59wE3JYU",
    thumbnail: "https://img.youtube.com/vi/Y5a59wE3JYU/hqdefault.jpg",
    thumbnailAlt: "mgk Trippie Redd beauty still",
    description: "Official video — beauty.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "halsey-so-good",
    tapeCode: "CDR-2604",
    title: "Halsey — So Good",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Halsey",
    videoUrl: "https://www.youtube.com/watch?v=N6tv11_KMiM",
    youtubeId: "N6tv11_KMiM",
    thumbnail: "https://img.youtube.com/vi/N6tv11_KMiM/hqdefault.jpg",
    thumbnailAlt: "Halsey So Good still",
    description: "Official video — So Good.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "le-sserafim-easy",
    tapeCode: "CDR-2605",
    title: "LE SSERAFIM — EASY",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "LE SSERAFIM",
    videoUrl: "https://www.youtube.com/watch?v=bNKXxwOQYB8",
    youtubeId: "bNKXxwOQYB8",
    thumbnail: "https://img.youtube.com/vi/bNKXxwOQYB8/hqdefault.jpg",
    thumbnailAlt: "LE SSERAFIM EASY still",
    description: "Official MV — EASY.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "doja-cat-agora-hills",
    tapeCode: "CDR-2606",
    title: "Doja Cat — Agora Hills",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Doja Cat",
    videoUrl: "https://www.youtube.com/watch?v=0c66ksfigtU",
    youtubeId: "0c66ksfigtU",
    thumbnail: "https://img.youtube.com/vi/0c66ksfigtU/hqdefault.jpg",
    thumbnailAlt: "Doja Cat Agora Hills still",
    description: "Official video — Agora Hills.",
    featured: true,
    priority: "hero",
    size: "lg",
  },
  {
    slug: "sza-nobody-gets-me",
    tapeCode: "CDR-2607",
    title: "SZA — Nobody Gets Me",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "SZA",
    videoUrl: "https://www.youtube.com/watch?v=NNd_ufPG3x4",
    youtubeId: "NNd_ufPG3x4",
    thumbnail: "https://img.youtube.com/vi/NNd_ufPG3x4/hqdefault.jpg",
    thumbnailAlt: "SZA Nobody Gets Me still",
    description: "Official video — Nobody Gets Me.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "kenzie-100-degrees",
    tapeCode: "CDR-2608",
    title: "kenzie — 100 degrees",
    category: "Music Videos",
    year: "2024",
    role: "Producer",
    client: "kenzie",
    videoUrl: "https://www.youtube.com/watch?v=VP8_YT4FKkQ",
    youtubeId: "VP8_YT4FKkQ",
    thumbnail: "https://img.youtube.com/vi/VP8_YT4FKkQ/hqdefault.jpg",
    thumbnailAlt: "kenzie 100 degrees still",
    description: "Official music video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "sza-psa-teaser",
    tapeCode: "CDR-2609",
    title: "SZA — PSA (teaser)",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "SZA",
    videoUrl: "https://www.youtube.com/watch?v=fC06V0ZLGwg",
    youtubeId: "fC06V0ZLGwg",
    thumbnail: "https://img.youtube.com/vi/fC06V0ZLGwg/hqdefault.jpg",
    thumbnailAlt: "SZA PSA teaser still",
    description: "Official teaser.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "charlie-puth-thats-not-how-this-works-dan-shay",
    tapeCode: "CDR-2610",
    title: "Charlie Puth — That's Not How This Works (feat. Dan + Shay)",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Charlie Puth",
    videoUrl: "https://www.youtube.com/watch?v=PAKFzFqJa58",
    youtubeId: "PAKFzFqJa58",
    thumbnail: "https://img.youtube.com/vi/PAKFzFqJa58/hqdefault.jpg",
    thumbnailAlt: "Charlie Puth Dan + Shay video still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "renee-rapp-snow-angel",
    tapeCode: "CDR-2611",
    title: "Reneé Rapp — Snow Angel",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Reneé Rapp",
    videoUrl: "https://www.youtube.com/watch?v=WZEHXFIa7Bk",
    youtubeId: "WZEHXFIa7Bk",
    thumbnail: "https://img.youtube.com/vi/WZEHXFIa7Bk/hqdefault.jpg",
    thumbnailAlt: "Reneé Rapp Snow Angel still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "lauv-all-4-nothing",
    tapeCode: "CDR-2612",
    title: "Lauv — All 4 Nothing (I'm So In Love)",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Lauv",
    videoUrl: "https://www.youtube.com/watch?v=AH8b7EynJ60",
    youtubeId: "AH8b7EynJ60",
    thumbnail: "https://img.youtube.com/vi/AH8b7EynJ60/hqdefault.jpg",
    thumbnailAlt: "Lauv All 4 Nothing still",
    description: "Official video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "honda-hr-v-twofold-mike-carson",
    tapeCode: "CDR-2613",
    title: "Honda HR-V — twofold (Mike Carson)",
    category: "Commercials",
    year: "2023",
    role: "Producer",
    client: "Honda",
    videoUrl: "https://www.youtube.com/watch?v=0xJjZSE39CU",
    youtubeId: "0xJjZSE39CU",
    thumbnail: "https://img.youtube.com/vi/0xJjZSE39CU/hqdefault.jpg",
    thumbnailAlt: "Honda HR-V spot still",
    description: "HR-V — twofold with Mike Carson.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "lauv-kids-are-born-stars",
    tapeCode: "CDR-2614",
    title: "Lauv — Kids Are Born Stars",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Lauv",
    videoUrl: "https://www.youtube.com/watch?v=QdTupNZjRcQ",
    youtubeId: "QdTupNZjRcQ",
    thumbnail: "https://img.youtube.com/vi/QdTupNZjRcQ/hqdefault.jpg",
    thumbnailAlt: "Lauv Kids Are Born Stars still",
    description: "Official video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "asap-rocky-pacsun",
    tapeCode: "CDR-2615",
    title: "A$AP Rocky — PacSun",
    category: "Commercials",
    year: "2022",
    role: "Producer",
    client: "PacSun",
    videoUrl: "https://www.youtube.com/watch?v=LVZagKk2mvI",
    youtubeId: "LVZagKk2mvI",
    thumbnail: "https://img.youtube.com/vi/LVZagKk2mvI/hqdefault.jpg",
    thumbnailAlt: "A$AP Rocky PacSun still",
    description: "Brand film — Rocky, PacSun.",
    featured: true,
    priority: "large",
    size: "lg",
  },
  {
    slug: "cadillac-lyriq-womens-history-month-goyo",
    tapeCode: "CDR-2616",
    title: "Cadillac LYRIQ — Women's History Month (Goyo)",
    category: "Commercials",
    year: "2023",
    role: "Producer",
    client: "Cadillac",
    videoUrl: "https://www.youtube.com/watch?v=Z1PluYiQHDM",
    youtubeId: "Z1PluYiQHDM",
    thumbnail: "https://img.youtube.com/vi/Z1PluYiQHDM/hqdefault.jpg",
    thumbnailAlt: "Cadillac LYRIQ film still",
    description: "LYRIQ x Goyo — Women's History Month.",
    featured: true,
    priority: "large",
    size: "lg",
  },
  {
    slug: "jack-harlow-nail-tech",
    tapeCode: "CDR-2617",
    title: "Jack Harlow — Nail Tech",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Jack Harlow",
    videoUrl: "https://www.youtube.com/watch?v=e2AeKIzfQus",
    youtubeId: "e2AeKIzfQus",
    thumbnail: "https://img.youtube.com/vi/e2AeKIzfQus/hqdefault.jpg",
    thumbnailAlt: "Jack Harlow Nail Tech still",
    description: "Official video.",
    featured: true,
    priority: "hero",
    size: "lg",
  },
  {
    slug: "saweetie-closer-feat-her",
    tapeCode: "CDR-2618",
    title: "Saweetie — Closer (feat. H.E.R.)",
    category: "Music Videos",
    year: "2022",
    role: "Producer",
    client: "Saweetie",
    videoUrl: "https://www.youtube.com/watch?v=ALO5efsHHQA",
    youtubeId: "ALO5efsHHQA",
    thumbnail: "https://img.youtube.com/vi/ALO5efsHHQA/hqdefault.jpg",
    thumbnailAlt: "Saweetie Closer still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "netflix-slate-true-crime",
    tapeCode: "CDR-2620",
    title: "Netflix — Home of True Crime (Slate)",
    category: "Commercials",
    year: "2024",
    role: "Producer",
    client: "Netflix",
    videoUrl: "https://www.youtube.com/watch?v=Yo3WUYBcNJI",
    youtubeId: "Yo3WUYBcNJI",
    thumbnail: "https://img.youtube.com/vi/Yo3WUYBcNJI/hqdefault.jpg",
    thumbnailAlt: "Netflix true crime slate still",
    description: "Slate announcement — true crime positioning.",
    featured: true,
    priority: "large",
    size: "lg",
  },
  {
    slug: "avril-lavigne-bite-me",
    tapeCode: "CDR-2621",
    title: "Avril Lavigne — Bite Me",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Avril Lavigne",
    videoUrl: "https://www.youtube.com/watch?v=ciqUEV9F0OY",
    youtubeId: "ciqUEV9F0OY",
    thumbnail: "https://img.youtube.com/vi/ciqUEV9F0OY/hqdefault.jpg",
    thumbnailAlt: "Avril Bite Me still",
    description: "Official video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "addison-rae-obsessed",
    tapeCode: "CDR-2622",
    title: "Addison Rae — Obsessed",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Addison Rae",
    videoUrl: "https://www.youtube.com/watch?v=PHr72DM762k",
    youtubeId: "PHr72DM762k",
    thumbnail: "https://img.youtube.com/vi/PHr72DM762k/hqdefault.jpg",
    thumbnailAlt: "Addison Rae Obsessed still",
    description: "Official music video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "travis-scott-ps5-unboxing-reimagined",
    tapeCode: "CDR-2623",
    title: "Travis Scott + Cactus Jack — PS5: Unboxing Reimagined",
    category: "Commercials",
    year: "2020",
    role: "Producer",
    client: "PlayStation / Travis Scott",
    videoUrl: "https://www.youtube.com/watch?v=dIaDGfE0G2A",
    youtubeId: "dIaDGfE0G2A",
    thumbnail: "https://img.youtube.com/vi/dIaDGfE0G2A/hqdefault.jpg",
    thumbnailAlt: "PS5 Travis Scott unboxing still",
    description: "Unboxing reimagined — Cactus Jack x PS5.",
    featured: true,
    priority: "hero",
    size: "xl",
  },
  {
    slug: "travis-barker-gimme-brain",
    tapeCode: "CDR-2625",
    title: "Travis Barker — Gimme Brain (feat. Lil Wayne & Rick Ross)",
    category: "Music Videos",
    year: "2019",
    role: "Producer",
    client: "Travis Barker",
    videoUrl: "https://www.youtube.com/watch?v=EXj_23pCUmE",
    youtubeId: "EXj_23pCUmE",
    thumbnail: "https://img.youtube.com/vi/EXj_23pCUmE/hqdefault.jpg",
    thumbnailAlt: "Travis Barker Gimme Brain still",
    description: "WSHH exclusive official video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "brandy-starting-now",
    tapeCode: "CDR-2626",
    title: "Brandy — Starting Now",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Brandy",
    videoUrl: "https://www.youtube.com/watch?v=7Ms-Y99bAi0",
    youtubeId: "7Ms-Y99bAi0",
    thumbnail: "https://img.youtube.com/vi/7Ms-Y99bAi0/hqdefault.jpg",
    thumbnailAlt: "Brandy Starting Now still",
    description: "Official video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "rich-brian-love-in-my-pocket",
    tapeCode: "CDR-2627",
    title: "Rich Brian — Love In My Pocket",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Rich Brian",
    videoUrl: "https://www.youtube.com/watch?v=oFHONLjD4MM",
    youtubeId: "oFHONLjD4MM",
    thumbnail: "https://img.youtube.com/vi/oFHONLjD4MM/hqdefault.jpg",
    thumbnailAlt: "Rich Brian Love In My Pocket still",
    description: "Official music video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "sofia-carson-hold-on-to-me",
    tapeCode: "CDR-2628",
    title: "Sofia Carson — Hold On To Me",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Sofia Carson",
    videoUrl: "https://www.youtube.com/watch?v=-nAlO_0HbxY",
    youtubeId: "-nAlO_0HbxY",
    thumbnail: "https://img.youtube.com/vi/-nAlO_0HbxY/hqdefault.jpg",
    thumbnailAlt: "Sofia Carson Hold On To Me still",
    description: "Official video.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "higher-learning-podcast-frequency",
    tapeCode: "CDR-2629",
    title: "Higher Frequency — Higher Learning Podcast",
    category: "Live / Rollouts",
    year: "2023",
    role: "Producer",
    client: "—",
    videoUrl: "https://www.youtube.com/watch?v=7ldm7FfUMM0",
    youtubeId: "7ldm7FfUMM0",
    thumbnail: "https://img.youtube.com/vi/7ldm7FfUMM0/hqdefault.jpg",
    thumbnailAlt: "Higher Learning podcast film still",
    description: "This Is Our Frequency — show branding piece.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "joji-diplo-daylight",
    tapeCode: "CDR-2630",
    title: "Joji & Diplo — Daylight",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Joji / Diplo",
    videoUrl: "https://www.youtube.com/watch?v=v97FPN2US2o",
    youtubeId: "v97FPN2US2o",
    thumbnail: "https://img.youtube.com/vi/v97FPN2US2o/hqdefault.jpg",
    thumbnailAlt: "Joji Diplo Daylight still",
    description: "Official music video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "vince-staples-law-of-averages",
    tapeCode: "CDR-2631",
    title: "Vince Staples — LAW OF AVERAGES",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Vince Staples",
    videoUrl: "https://www.youtube.com/watch?v=oTri3zbX-R8",
    youtubeId: "oTri3zbX-R8",
    thumbnail: "https://img.youtube.com/vi/oTri3zbX-R8/hqdefault.jpg",
    thumbnailAlt: "Vince Staples Law of Averages still",
    description: "Official video.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "noa-kirel-please-dont-suck",
    tapeCode: "CDR-2633",
    title: "Noa Kirel — Please Don't Suck",
    category: "Music Videos",
    year: "2023",
    role: "Producer",
    client: "Noa Kirel",
    videoUrl: "https://www.youtube.com/watch?v=5GUYcnAMZ5c",
    youtubeId: "5GUYcnAMZ5c",
    thumbnail: "https://img.youtube.com/vi/5GUYcnAMZ5c/hqdefault.jpg",
    thumbnailAlt: "Noa Kirel Please Don't Suck still",
    description: "Official music video.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "mellon-betise",
    tapeCode: "CDR-2634",
    title: "Bêtise",
    category: "Narrative",
    year: "2019",
    role: "Producer",
    client: "Mellon",
    videoUrl: "https://vimeo.com/317162116",
    vimeoId: "317162116",
    thumbnail:
      "https://i.vimeocdn.com/video/950537851-4a9fecd4fca49586abffb94f686219fe3a842436069acc666ba63baf568ce2f5-d_640?region=us",
    thumbnailAlt: "Bêtise short still",
    description: "Writer & director Grant Mellon — narrative short.",
    featured: false,
    priority: "large",
    size: "lg",
  },
  {
    slug: "charlie-puth-free-one-and-only-ivan",
    tapeCode: "CDR-2635",
    title: "Charlie Puth — Free (The One and Only Ivan)",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Charlie Puth",
    videoUrl: "https://www.youtube.com/watch?v=QoohbHFIS38",
    youtubeId: "QoohbHFIS38",
    thumbnail: "https://img.youtube.com/vi/QoohbHFIS38/hqdefault.jpg",
    thumbnailAlt: "Charlie Puth Free still",
    description: "From The One and Only Ivan.",
    featured: false,
    priority: "standard",
    size: "md",
  },
  {
    slug: "alaina-castillo-pocket-locket",
    tapeCode: "CDR-2638",
    title: "Alaina Castillo — pocket locket",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "Alaina Castillo",
    videoUrl: "https://www.youtube.com/watch?v=rMz1a078R0U",
    youtubeId: "rMz1a078R0U",
    thumbnail: "https://img.youtube.com/vi/rMz1a078R0U/hqdefault.jpg",
    thumbnailAlt: "Alaina Castillo pocket locket still",
    description: "Official video.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "madeintyo-bet-uncut",
    tapeCode: "CDR-2641",
    title: "MadeinTYO — BET Uncut (feat. Chance the Rapper & Smino)",
    category: "Music Videos",
    year: "2020",
    role: "Producer",
    client: "MadeinTYO",
    videoUrl: "https://www.youtube.com/watch?v=WxsWU2_btic",
    youtubeId: "WxsWU2_btic",
    thumbnail: "https://img.youtube.com/vi/WxsWU2_btic/hqdefault.jpg",
    thumbnailAlt: "MadeinTYO BET Uncut still",
    description: "Official video.",
    featured: false,
    priority: "small",
    size: "sm",
  },
  {
    slug: "why-dont-we-slow-down",
    tapeCode: "CDR-2642",
    title: "Why Don't We — Slow Down",
    category: "Music Videos",
    year: "2021",
    role: "Producer",
    client: "Why Don't We",
    videoUrl: "https://www.youtube.com/watch?v=46ISK1g54Fc",
    youtubeId: "46ISK1g54Fc",
    thumbnail: "https://img.youtube.com/vi/46ISK1g54Fc/hqdefault.jpg",
    thumbnailAlt: "Why Don't We Slow Down still",
    description: "Official music video.",
    featured: false,
    priority: "small",
    size: "sm",
  },
];

export function getYoutubeVideoId(videoUrl: string): string | null {
  const m = videoUrl.match(
    /(?:youtube\.com\/watch\?[^#]*?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
  );
  return m ? m[1] : null;
}

export function getVimeoVideoId(videoUrl: string): string | null {
  const m = videoUrl.match(/vimeo\.com\/(?:video\/)?(\d+)/);
  return m ? m[1] : null;
}

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

/** Same order as `projects` in this file (stable list order). */
export function getProjectsForArchive(): Project[] {
  return [...projects];
}

export type VideoEmbed =
  | { kind: "youtube"; src: string }
  | { kind: "vimeo"; src: string }
  | { kind: "file"; src: string }
  | { kind: "unknown"; src: null };

/**
 * SWAP: extend if you host elsewhere (Wistia, etc.).
 */
export function getVideoEmbed(videoUrl: string): VideoEmbed {
  const yt = videoUrl.match(
    /(?:youtube\.com\/watch\?[^#]*?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
  );
  if (yt) {
    return {
      kind: "youtube",
      src: `https://www.youtube.com/embed/${yt[1]}?rel=0&modestbranding=1`,
    };
  }
  const vm = videoUrl.match(/vimeo\.com\/(?:video\/)?(\d+)/);
  if (vm) {
    return {
      kind: "vimeo",
      src: `https://player.vimeo.com/video/${vm[1]}?badge=0`,
    };
  }
  if (/\.(mp4|webm|ogg)(\?|$)/i.test(videoUrl)) {
    return { kind: "file", src: videoUrl };
  }
  return { kind: "unknown", src: null };
}
